In [2]:
import torch

In [3]:
print(torch.__version__)

2.8.0+cpu


In [4]:
torch.cuda.is_available()

False

In [5]:
# RANK, AXES, AND RESHAPING
t=torch.tensor([
    [1,1,1,1],
    [2,2,2,2],
    [3,3,3,3],
    [4,4,4,4]
])

In [6]:
t.size()
t.shape

torch.Size([4, 4])

In [7]:
# number of elements in tensor
t.numel()

16

In [8]:
# reshaping
t.reshape(1,16)

tensor([[1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4]])

In [9]:
t.reshape(2,8)

tensor([[1, 1, 1, 1, 2, 2, 2, 2],
        [3, 3, 3, 3, 4, 4, 4, 4]])

In [10]:
# changing the rank of the tensor
t.reshape(2,2,4)

tensor([[[1, 1, 1, 1],
         [2, 2, 2, 2]],

        [[3, 3, 3, 3],
         [4, 4, 4, 4]]])

In [11]:
t.squeeze()

tensor([[1, 1, 1, 1],
        [2, 2, 2, 2],
        [3, 3, 3, 3],
        [4, 4, 4, 4]])

In [12]:
t.unsqueeze(dim=1)

tensor([[[1, 1, 1, 1]],

        [[2, 2, 2, 2]],

        [[3, 3, 3, 3]],

        [[4, 4, 4, 4]]])

In [13]:


#   tensor batch processing of flatten of CNN

t1=torch.tensor([
    [1,1,1,1],
    [2,2,2,2],                #     <- image 1 of array value
    [1,1,1,1],
    [2,2,2,2]
])

t2=torch.tensor([
    [1,1,1,1],
    [2,2,2,2],                   #     <- image 2 of array value
    [1,1,1,1],
    [2,2,2,2]
])

t3=torch.tensor([
    [1,1,1,1],
    [2,2,2,2],                 #     <- image 2 of array value
    [1,1,1,1],
    [2,2,2,2]
])

t=torch.stack((t1,t2,t3))
print(t,"\n")
print(t.size())

tensor([[[1, 1, 1, 1],
         [2, 2, 2, 2],
         [1, 1, 1, 1],
         [2, 2, 2, 2]],

        [[1, 1, 1, 1],
         [2, 2, 2, 2],
         [1, 1, 1, 1],
         [2, 2, 2, 2]],

        [[1, 1, 1, 1],
         [2, 2, 2, 2],
         [1, 1, 1, 1],
         [2, 2, 2, 2]]]) 

torch.Size([3, 4, 4])


In [14]:
# Adding a color channel
t=t.reshape(3,1,4,4)
print(t)

tensor([[[[1, 1, 1, 1],
          [2, 2, 2, 2],
          [1, 1, 1, 1],
          [2, 2, 2, 2]]],


        [[[1, 1, 1, 1],
          [2, 2, 2, 2],
          [1, 1, 1, 1],
          [2, 2, 2, 2]]],


        [[[1, 1, 1, 1],
          [2, 2, 2, 2],
          [1, 1, 1, 1],
          [2, 2, 2, 2]]]])


In [15]:
# first batch
t[0]

tensor([[[1, 1, 1, 1],
         [2, 2, 2, 2],
         [1, 1, 1, 1],
         [2, 2, 2, 2]]])

In [16]:
# first channel
t[0] [0]

tensor([[1, 1, 1, 1],
        [2, 2, 2, 2],
        [1, 1, 1, 1],
        [2, 2, 2, 2]])

In [21]:
# first row of pixel height
t[0] [0] [0]

tensor([1, 1, 1, 1])

In [18]:
# first pixel of first batch image first channnels first row of pixels
t[0][0][0][0]

tensor(1)

In [24]:
# this is how a batch of image is flattened
t.flatten(start_dim=1)

tensor([[1, 1, 1, 1, 2, 2, 2, 2, 1, 1, 1, 1, 2, 2, 2, 2],
        [1, 1, 1, 1, 2, 2, 2, 2, 1, 1, 1, 1, 2, 2, 2, 2],
        [1, 1, 1, 1, 2, 2, 2, 2, 1, 1, 1, 1, 2, 2, 2, 2]])