In [1]:
import torch

In [2]:
print(torch.__version__)

2.8.0+cpu


In [3]:
torch.cuda.is_available()

False

In [4]:
# RANK, AXES, AND RESHAPING
t=torch.tensor([
    [1,1,1,1],
    [2,2,2,2],
    [3,3,3,3],
    [4,4,4,4]
])

In [5]:
t.size()
t.shape

torch.Size([4, 4])

In [6]:
# number of elements in tensor
t.numel()

16

In [7]:
# reshaping
t.reshape(1,16)

tensor([[1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4]])

In [8]:
t.reshape(2,8)

tensor([[1, 1, 1, 1, 2, 2, 2, 2],
        [3, 3, 3, 3, 4, 4, 4, 4]])

In [9]:
# changing the rank of the tensor
t.reshape(2,2,4)

tensor([[[1, 1, 1, 1],
         [2, 2, 2, 2]],

        [[3, 3, 3, 3],
         [4, 4, 4, 4]]])

In [10]:
t.squeeze()

tensor([[1, 1, 1, 1],
        [2, 2, 2, 2],
        [3, 3, 3, 3],
        [4, 4, 4, 4]])

In [11]:
t.unsqueeze(dim=1)

tensor([[[1, 1, 1, 1]],

        [[2, 2, 2, 2]],

        [[3, 3, 3, 3]],

        [[4, 4, 4, 4]]])

In [12]:


#   tensor batch processing of flatten of CNN

t1=torch.tensor([
    [1,1,1,1],
    [2,2,2,2],                #     <- image 1 of array value
    [1,1,1,1],
    [2,2,2,2]
])

t2=torch.tensor([
    [1,1,1,1],
    [2,2,2,2],                   #     <- image 2 of array value
    [1,1,1,1],
    [2,2,2,2]
])

t3=torch.tensor([
    [1,1,1,1],
    [2,2,2,2],                 #     <- image 2 of array value
    [1,1,1,1],
    [2,2,2,2]
])

t=torch.stack((t1,t2,t3))
print(t,"\n")
print(t.size())

tensor([[[1, 1, 1, 1],
         [2, 2, 2, 2],
         [1, 1, 1, 1],
         [2, 2, 2, 2]],

        [[1, 1, 1, 1],
         [2, 2, 2, 2],
         [1, 1, 1, 1],
         [2, 2, 2, 2]],

        [[1, 1, 1, 1],
         [2, 2, 2, 2],
         [1, 1, 1, 1],
         [2, 2, 2, 2]]]) 

torch.Size([3, 4, 4])


In [13]:
# Adding a color channel
t=t.reshape(3,1,4,4)
print(t)

tensor([[[[1, 1, 1, 1],
          [2, 2, 2, 2],
          [1, 1, 1, 1],
          [2, 2, 2, 2]]],


        [[[1, 1, 1, 1],
          [2, 2, 2, 2],
          [1, 1, 1, 1],
          [2, 2, 2, 2]]],


        [[[1, 1, 1, 1],
          [2, 2, 2, 2],
          [1, 1, 1, 1],
          [2, 2, 2, 2]]]])


In [14]:
# first batch
t[0]

tensor([[[1, 1, 1, 1],
         [2, 2, 2, 2],
         [1, 1, 1, 1],
         [2, 2, 2, 2]]])

In [15]:
# first channel
t[0] [0]

tensor([[1, 1, 1, 1],
        [2, 2, 2, 2],
        [1, 1, 1, 1],
        [2, 2, 2, 2]])

In [16]:
# first row of pixel height
t[0] [0] [0]

tensor([1, 1, 1, 1])

In [17]:
# first pixel of first batch image first channnels first row of pixels
t[0][0][0][0]

tensor(1)

In [18]:
# this is how a batch of image is flattened
t.flatten(start_dim=1)

tensor([[1, 1, 1, 1, 2, 2, 2, 2, 1, 1, 1, 1, 2, 2, 2, 2],
        [1, 1, 1, 1, 2, 2, 2, 2, 1, 1, 1, 1, 2, 2, 2, 2],
        [1, 1, 1, 1, 2, 2, 2, 2, 1, 1, 1, 1, 2, 2, 2, 2]])

In [19]:
# Reduction Functions(Aggregations)
# all thease methods reduces the tensors as a single component value
t=torch.tensor([
    [0,1,0],
    [2,0,2],
    [0,3,0]
],dtype=torch.float32)

print(t)

tensor([[0., 1., 0.],
        [2., 0., 2.],
        [0., 3., 0.]])


In [20]:
t.sum()

tensor(8.)

In [21]:
t.mean()

tensor(0.8889)

In [22]:
t.std()

tensor(1.1667)

In [23]:
t.prod()

tensor(0.)

In [24]:
t.sum(dim=0)

tensor([2., 4., 2.])

In [25]:
t.sum(dim=1)

tensor([1., 4., 3.])

In [26]:
# Argmax Function

t.max()

tensor(3.)

In [27]:
t.argmax()

tensor(7)

In [28]:
t.max(dim=0)

torch.return_types.max(
values=tensor([2., 3., 2.]),
indices=tensor([1, 2, 1]))

In [29]:
t.argmax(dim=0)

tensor([1, 2, 1])

In [30]:
t.max(dim=1)

torch.return_types.max(
values=tensor([1., 2., 3.]),
indices=tensor([1, 0, 1]))

In [31]:
t.argmax(dim=1)

tensor([1, 0, 1])

In [32]:
# Converting tensor component to numerical values(only works with scalar value tensor)
t.max().item()

3.0

In [33]:
t.mean(dim=0).tolist()

[0.6666666865348816, 1.3333333730697632, 0.6666666865348816]

In [34]:
t.mean(dim=0).numpy()

array([0.6666667, 1.3333334, 0.6666667], dtype=float32)